# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

- task: CmdLine@2
  inputs:
    script: 'curl https://mill.jfrog.team:12734/artifactory -vvv'
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
