# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

steps:
- task: CmdLine@2
  inputs:
    script: 'curl https://inochoi2.jfrog.io/artifactory -vvv'

- task: ArtifactoryGenericDownload@3
  inputs:
    connection: 'inochoi2.jfrog.io'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "example-repo-local/*.td",
            "target": "/Users/inhoc/Downloads/myagent/"
          }
        ]
      }
    failNoOp: true
- task: ArtifactoryGenericUpload@2
  inputs:
    artifactoryService: 'inochoi2.jfrog.io'
    specSource: 'taskConfiguration'
    fileSpec: |
      {
        "files": [
          {
            "pattern": "/Users/inhoc/Downloads/myagent/*.sh",
            "target": "example-repo-local"
          }
        ]
      }
    failNoOp: true

- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'inochoi2.jfrog.io'
    buildName: 'test'
    buildNumber: '1'